In [13]:
import numpy as np
x = 4
y = 4
a = np.zeros((x,y), dtype=np.float64)
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Clase Grafo
* Uso de Matriz de Adjacencia y se marca con 1 en cada interseccion entre x & y 
* Grafo, constructor y 2 funciones
* funcion BFS

In [14]:
class Grafo:
#self nombre del constructor 
  def __init__(grafo, vertices):
    grafo.Numvertices = vertices
    grafo.matrizAdj = np.zeros((vertices,vertices), dtype=np.float64)

  def adicionarAresta(grafo, v, v2, aresta):
        grafo.matrizAdj[v, v2] = aresta
        #if grafo.matrizAdj[v2, v] == 0:
            # grafo.matrizAdj[v2, v] = 1
        
  def imprimeGrafo(grafo):
        for i in range(grafo.Numvertices):
            #print(i)
            for j in range(grafo.Numvertices):
                print( "->")
                print(grafo.matrizAdj[i,j], end="")                    
            print("\n")
            
  def BFS(grafo, start):
        visited = [False] * grafo.Numvertices
        q = [start]
        visited[start] = True
 
        while q:
            vis = q[0]
 
            # Print current node
            print(vis, end = ' ')
            q.pop(0)
             

            for i in range(grafo.Numvertices):
                if (grafo.matrizAdj[vis][i] == 1 and
                      (not visited[i])):
                           
                    q.append(i)
                    visited[i] = True  

* Main Ejecutar todo el codigo

In [15]:
p1 = Grafo(4)
p1.adicionarAresta(0, 1, 1)
p1.adicionarAresta(0, 2, 1)
p1.adicionarAresta(1, 3, 1)
p1.imprimeGrafo()
print(p1.matrizAdj)
p1.BFS(0)

->
0.0->
1.0->
1.0->
0.0

->
0.0->
0.0->
0.0->
1.0

->
0.0->
0.0->
0.0->
0.0

->
0.0->
0.0->
0.0->
0.0

[[0. 1. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
0 1 2 3 